language: node_js
node_js: "lts/*"
branches:
  only:
    - master
cache: npm

jobs:
  include:
    # Deploy
    - stage: deploy
      name: NPM
      script: skip
      before_deploy:
        - echo -e "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc 2> /dev/null
        - "npm run build"
      deploy:
        provider: script
        script:
          - "npm publish || true"
        skip_cleanup: true
        on:
          branch: master
    - script: skip
      name: GITHUB
      before_deploy:
        - echo -e "//npm.pkg.github.com/:_authToken=${GITHUB_PACKAGE_TOKEN}\nregistry=https://npm.pkg.github.com/hpi-schul-cloud" > .npmrc 2> /dev/null
        - "npm run build"
      deploy:
        provider: script
        script:
          - "npm publish || true"
        skip_cleanup: true
        on:
          branch: master
